update workflow to fail when codecoverage less than 60%

diff --git a/.github/workflows/superlinter.yml b/.github/workflows/superlinter.yml
--- a/.github/workflows/superlinter.yml
+++ b/.github/workflows/superlinter.yml
@@ -31,12 +31,7 @@ jobs:
         run: |
           echo "QcademyMailUsername=${QcademyMailUsername}" >> $GITHUB_ENV
           echo "QcademyMailPassword=${QcademyMailPassword}" >> $GITHUB_ENV
-
-      - name: Print email username and password
-        run: |
-          echo "Email Username: $QcademyMailUsername"
-          echo "Email Password: $QcademyMailPassword"
-
+          
       - name: Build with Maven
         run: mvn -f backend/pom.xml clean install
 
@@ -48,3 +43,12 @@ jobs:
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           files: ./backend/target/site/jacoco/jacoco.xml
+
+      - name: Check Code Coverage
+        run: |
+          CODE_COVERAGE=$(grep -Po '<line.*?>(\d+)<\/line>' ./backend/target/site/jacoco/jacoco.xml | awk '{ covered += $1 } END { print int(covered / NR) }')
+
+          if [ "$CODE_COVERAGE" -lt 60 ]; then
+            echo "Code coverage is below 60% ($CODE_COVERAGE%). Failing the workflow."
+            exit 1
+          fi
